"""
Part verification module for GenCAD.
Verifies generated FreeCAD code against user request using LLM.
Returns either "verified - ok" or corrected code.
"""

from langchain_core.messages import SystemMessage, HumanMessage
import base64
import os
from pathlib import Path


def _load_verify_instruction() -> str:
    """Load the verify instruction prompt from file."""
    instruction_path = Path(__file__).parent.parent / "prompts" / "verify_instruction.txt"
    if instruction_path.exists():
        return instruction_path.read_text()
    return ""


VERIFY_INSTRUCTION = _load_verify_instruction()

VERIFICATION_SYSTEM_PROMPT = f"""You are a code verification assistant for FreeCAD Python code generation.

Your task is to check whether the generated FreeCAD Python code correctly implements the user's request.

Check the following:
1. All parameters, and values match the user's request

If the code is correct and matches the request, respond exactly with: verified - ok

If the code needs corrections, respond with the FULL corrected FreeCAD Python code only (no explanations, no markdown fences).

IMPORTANT: Your response MUST be either exactly "verified - ok" or the corrected FreeCAD code.

"""
VERIFICATION_SYSTEM_PROMPT_PLUS_INSTRUCTION = VERIFICATION_SYSTEM_PROMPT + VERIFY_INSTRUCTION

VISUAL_VERIFICATION_SYSTEM_PROMPT = f"""You are an expert CAD engineer working with FreeCAD 1.0.1. with vision capabilities.

You are given screenshots of a 3D part generated by FreeCAD and code and the original user request.

Your task is to verify whether the visible geometry in the screenshots matches what the user requested.

Check the following:
1. Overall shape and structure matches the request
2. IMPORTANT - Key features are present (holes, slots, fillets, etc.). Check it twice!!!
3. Proportions and relative sizes look correct (check elements parameters and its visual relative sizes)
4. No obvious visual defects or missing geometry
5. Composition and semantic orientation of elements (how elements should be orientiated in part)
6. No redundant holes, pads, etc.
7. No redundant gaps between elements.
8. No redundant overlaps between elements.
9. All parameters, and values match the user's request

IMPORTANT: BE PRECISE!

Also review the generated code to ensure it matches the request parameters.

If the screenshots and code both correctly implement the user request, respond exactly with: verified - ok

If there are visual discrepancies or code issues, respond with the FULL corrected FreeCAD Python code that would produce the correct geometry (no explanations, no markdown fences).

IMPORTANT: Your response MUST be either exactly "verified - ok" or the corrected FreeCAD code.

"""
VISUAL_VERIFICATION_SYSTEM_PROMPT_PLUS_INSTRUCTION = VISUAL_VERIFICATION_SYSTEM_PROMPT + VERIFY_INSTRUCTION


def verify_generated_code(user_request: str, generated_code: str) -> dict:
    """Verify generated code against user request using LLM.

    Args:
        user_request: The original user description/request
        generated_code: The generated FreeCAD Python code

    Returns:
        dict with:
            - 'verified': bool — True if code passed verification
            - 'corrected_code': str or None — corrected code if verification failed
            - 'raw_response': str — the raw LLM response
    """
    from src.llm_client import _invoke_llm

    # Build the verification prompt
    user_prompt = f"""Request: {user_request}

Code:
{generated_code}
"""

    messages = [
        SystemMessage(content=VERIFICATION_SYSTEM_PROMPT_PLUS_INSTRUCTION),
        HumanMessage(content=user_prompt),
    ]

    try:
        # import debugpy; debugpy.breakpoint()
        response = _invoke_llm(messages)
        response = response.strip()

        # Check if verified
        if response.lower() == "verified - ok":
            return {
                "verified": True,
                "corrected_code": None,
                "raw_response": response,
            }

        # Otherwise, treat the response as corrected code
        # Clean markdown code fences if present
        response = _clean_code_fences(response)

        return {
            "verified": False,
            "corrected_code": response,
            "raw_response": response,
        }

    except Exception as e:
        # If LLM call fails, assume verified to avoid blocking generation
        return {
            "verified": True,
            "corrected_code": None,
            "raw_response": f"Verification LLM call failed: {str(e)}",
        }


def verify_part_visual(screenshot_paths: list, user_request: str, generated_code: str) -> dict:
    """Verify generated part visually using screenshots from multiple views and user request via VLM.

    Args:
        screenshot_paths: List of paths to screenshot images (isometric, top, front, right, bottom, rear, left)
        user_request: The original user description/request
        generated_code: The generated FreeCAD Python code

    Returns:
        dict with:
            - 'verified': bool — True if visual verification passed
            - 'corrected_code': str or None — corrected code if verification failed
            - 'raw_response': str — the raw LLM response
    """
    from src.llm_client import _invoke_llm
    from src.load_environment import load_env
    from src.llm_client import _reload_config
    
    # Reload config to get latest VLM model settings
    _reload_config()
    
    # Determine VLM model based on current provider
    current_use_ollama = getattr(load_env, 'USE_OLLAMA', False)
    current_use_openrouter = getattr(load_env, 'USE_OPENROUTER', False)
    current_use_routerairu = getattr(load_env, 'USE_ROUTERAIRU', False)
    
    if current_use_ollama:
        vlm_model = getattr(load_env, 'OLLAMA_VLM_MODEL', 'qwen3.6')
    elif current_use_openrouter:
        vlm_model = getattr(load_env, 'OPENROUTER_VLM_MODEL', 'qwen/qwen3.6-plus')
    elif current_use_routerairu:
        vlm_model = getattr(load_env, 'ROUTERAIRU_VLM_MODEL', 'qwen/qwen3.6-plus')
    else:
        vlm_model = None  # Use default model

    if not screenshot_paths:
        return {
            "verified": True,
            "corrected_code": None,
            "raw_response": "Visual verification skipped: no screenshots provided",
        }

    # Check that all screenshot files exist
    valid_paths = [p for p in screenshot_paths if os.path.exists(p)]
    if not valid_paths:
        return {
            "verified": True,
            "corrected_code": None,
            "raw_response": f"Visual verification skipped: no valid screenshot files found",
        }

    # Build the verification prompt
    # You are given {len(valid_paths)} screenshots of the generated part from different views (isometric, top, front, right, bottom, rear, left).
    user_prompt = f"""
You are given {len(valid_paths)} screenshots of the generated part from view (isometric).

User Request: {user_request}

Generated Code:
{generated_code}

"""

    messages = [
        SystemMessage(content=VISUAL_VERIFICATION_SYSTEM_PROMPT_PLUS_INSTRUCTION),
        HumanMessage(content=user_prompt, additional_kwargs={"images": valid_paths}),
    ]

    try:
        # import debugpy; debugpy.breakpoint()
        response = _invoke_llm(messages, model=vlm_model)
        response = response.strip()

        # Check if verified
        if response.lower() == "verified - ok":
            return {
                "verified": True,
                "corrected_code": None,
                "raw_response": response,
            }

        # Otherwise, treat the response as corrected code
        response = _clean_code_fences(response)

        return {
            "verified": False,
            "corrected_code": response,
            "raw_response": response,
        }

    except Exception as e:
        # If LLM call fails, assume verified to avoid blocking generation
        return {
            "verified": True,
            "corrected_code": None,
            "raw_response": f"Visual verification LLM call failed: {str(e)}",
        }


def _clean_code_fences(code: str) -> str:
    """Remove markdown code fences and language prefix."""
    # import debugpy; debugpy.breakpoint()
    if code.startswith("```"):
        code = code.strip("`\n ")
        if code.lower().startswith("python"):
            code = code[len("python") :].lstrip()
    return code
